# Generated by Django 6.0.6 on 2026-07-07 07:38

from django.db import migrations


def copy_profiles(apps, _schema_editor):
    old_profile = apps.get_model("oc_lettings_site", "Profile")
    new_profile = apps.get_model("profiles", "Profile")

    for profile in old_profile.objects.all():
        new_profile.objects.create(
            id=profile.id,
            user_id=profile.user_id,
            favorite_city=profile.favorite_city,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_profiles),
    ]