# Generated by Django 6.0.6 on 2026-07-07 07:33
"""
Data migration to transfer Address and Letting records after moving
the models from the oc_lettings_site app to the lettings app.
"""

from django.db import migrations


def copy_addresses(apps, _schema_editor):
    """
    Copy existing Address records from the old app to the new lettings app.
    """
    old_address = apps.get_model("oc_lettings_site", "Address")
    new_address = apps.get_model("lettings", "Address")

    for address in old_address.objects.all():
        new_address.objects.create(
            id=address.id,
            number=address.number,
            street=address.street,
            city=address.city,
            state=address.state,
            zip_code=address.zip_code,
            country_iso_code=address.country_iso_code,
        )


def copy_lettings(apps, _schema_editor):
    """
    Copy existing Letting records from the old app to the new lettings app.
    """
    old_lettings = apps.get_model("oc_lettings_site", "Letting")
    new_lettings = apps.get_model("lettings", "Letting")

    for letting in old_lettings.objects.all():
        new_lettings.objects.create(
            id=letting.id,
            title=letting.title,
            address_id=letting.address_id,
        )


def reverse(apps, _schema_editor):
    """
    Remove migrated Address and Letting records from the new app.
    """
    new_address = apps.get_model("lettings", "Address")
    new_lettings = apps.get_model("lettings", "Letting")

    new_lettings.objects.all().delete()
    new_address.objects.all().delete()


class Migration(migrations.Migration):
    """
    Transfer Address and Letting records from the old app to the new lettings app
    after the model refactoring.
    """
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_addresses, reverse),
        migrations.RunPython(copy_lettings, migrations.RunPython.noop),
    ]