# Generated by Django 6.0.6 on 2026-07-07 07:54
"""
Remove legacy models from the oc_lettings_site app after migrating
their data to the new lettings and profiles apps.
"""

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove legacy models from the oc_lettings_site app after their migration
    to the dedicated lettings and profiles apps.
    """
    dependencies = [
        ("oc_lettings_site", "0002_alter_address_id_alter_letting_address_and_more"),
        ("lettings", "0002_copy_data"),
        ("profiles", "0002_copy_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
